# Generated by Django 3.1.6 on 2022-11-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0014_auto_20221106_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liker',
            new_name='author',
        ),
    ]
